name: run-tests-like-there-is-no-tomorrow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout and setup
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-Java@v3
        with:
          Java-version: '17'
          distribution: temurin

      - name: Build with Maven
        run: mvn package

      - name: List Files in target Directory
        run: ls -R target

      - name: Run JUnit tests
        run:  mvn test

      - name: List Test Report Files
        run: ls -R target/surefire-reports

      - name: Report
        uses: dorny/test-reporter@v1.7.0
        if: always()
        with:
          name: Maven Tests
          path: target/surefire-reports/*.xml
          reporter: java-junit
          fail-on-error: true
