name: run-tests-like-there-is-no-tomorrow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout and setup
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-Java@v4
        with:
          Java-version: '19'
          distribution: oracle

      - name: Build with Maven
        run: mvn package

      - name: Run JUnit tests
        run:  mvn test